version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 30s
      timeout: 30s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo_server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./base-front
      dockerfile: Dockerfile
    container_name: todo_front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

    
